version: '3.7'

services:
  mjpeg:
    hostname: mjpeg
    restart: unless-stopped
    image: thespaghettidetective/mjpg-streamer
    ports:
      - "1989:8080"
    volumes:
     - ./:/app
    command: sh -c "/mjpg-streamer/mjpg_streamer -o '/mjpg-streamer/output_http.so -w /mjpg-streamer/www' -i '/mjpg-streamer/input_file.so -f /app/data/jpgs -e -d 0.1'"
