version: '2.4'

services:
  ml:
    hostname: ml
    runtime: nvidia
    restart: unless-stopped
    build:
      context: .
    tty: true
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    command: bash -c "sleep 1000000"
        #command: bash -c "./runapp.sh"
